[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000

solc_version='0.8.20'

[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia", url = "https://api-sepolia.etherscan.io/api" }

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config